version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vinaacademy-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-vinaacademy}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: vinaacademy-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vinaacademy-backend
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-vinaacademy}
      DATABASE_USERNAME: ${POSTGRES_USER:-postgres}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      HMAC_SECRET: ${HMAC_SECRET:-super-secret-key-for-hmac}
      UPLOAD_DIR: ${UPLOAD_DIR:-/vinaacademy/uploads}
      HLS_OUTPUT_DIR: ${HLS_OUTPUT_DIR:-/vinaacademy/hls}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SPRING_PROFILES_ACTIVE: prd
    volumes:
      - uploads_data:/vinaacademy/uploads
      - hls_data:/vinaacademy/hls
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend:8080/api/v1}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
    container_name: vinaacademy-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  uploads_data:
  hls_data:

networks:
  app-network:
    driver: bridge